// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include <libintl.h>
#include "fltkgui.hpp"
#include <FL/Fl_JPEG_Image.H>
#include <FL/Fl_Native_File_Chooser.H>

void FltkGui::cb_fileOpen_i(Fl_Menu_*, void*) {
  openJpegImage();
}
void FltkGui::cb_fileOpen(Fl_Menu_* o, void* v) {
  ((FltkGui*)(o->parent()->user_data()))->cb_fileOpen_i(o,v);
}

void FltkGui::cb_Quit_i(Fl_Menu_*, void*) {
  mainWindow->hide();
}
void FltkGui::cb_Quit(Fl_Menu_* o, void* v) {
  ((FltkGui*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

unsigned char FltkGui::menu__i18n_done = 0;
Fl_Menu_Item FltkGui::menu_[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open...", 0,  (Fl_Callback*)FltkGui::cb_fileOpen, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  (Fl_Callback*)FltkGui::cb_Quit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* FltkGui::fileOpen = FltkGui::menu_ + 1;

unsigned char FltkGui::menu_Unit_i18n_done = 0;
Fl_Menu_Item FltkGui::menu_Unit[] = {
 {"mm", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"in", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void FltkGui::cb_generateGcodeButton_i(Fl_Button*, void*) {
  selectedOutputGenerator = "gcode";
generateOutput("polyline",
               outputFileNameInput->value());
}
void FltkGui::cb_generateGcodeButton(Fl_Button* o, void* v) {
  ((FltkGui*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_generateGcodeButton_i(o,v);
}

unsigned char FltkGui::menu_Drawer_i18n_done = 0;
Fl_Menu_Item FltkGui::menu_Drawer[] = {
 {"PolyLine", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Crosses", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

FltkGui::FltkGui() {
  { mainWindow = new Fl_Window(660, 610, gettext("Pic2Lines"));
    mainWindow->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 660, 20);
      if (!menu__i18n_done) {
        int i=0;
        for ( ; i<3; i++)
          if (menu_[i].label())
            menu_[i].label(gettext(menu_[i].label()));
        menu__i18n_done = 1;
      }
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(210, 35, 425, 570, gettext("Output"));
      o->box(FL_THIN_DOWN_FRAME);
      { Fl_Choice* o = new Fl_Choice(315, 60, 130, 16, gettext("Unit"));
        o->down_box(FL_BORDER_BOX);
        if (!menu_Unit_i18n_done) {
          int i=0;
          for ( ; i<2; i++)
            if (menu_Unit[i].label())
              menu_Unit[i].label(gettext(menu_Unit[i].label()));
          menu_Unit_i18n_done = 1;
        }
        o->menu(menu_Unit);
      } // Fl_Choice* o
      { Fl_Spinner* o = new Fl_Spinner(315, 85, 115, 25, gettext("Width"));
        o->type(1);
        o->step(0.1);
      } // Fl_Spinner* o
      { new Fl_Spinner(315, 120, 115, 25, gettext("Height"));
      } // Fl_Spinner* o
      { Fl_Tabs* o = new Fl_Tabs(215, 170, 415, 435);
        { Fl_Group* o = new Fl_Group(215, 193, 400, 412, gettext("G-Code"));
          { laserOnCommandInput = new Fl_Input(390, 215, 160, 30, gettext("Laser on"));
          } // Fl_Input* laserOnCommandInput
          { laserOffCommandInput = new Fl_Input(390, 245, 160, 25, gettext("Laser off"));
          } // Fl_Input* laserOffCommandInput
          { maxPowerSlider = new Fl_Value_Slider(390, 274, 160, 21, gettext("Max power"));
            maxPowerSlider->type(1);
            maxPowerSlider->minimum(1);
            maxPowerSlider->step(1);
            maxPowerSlider->value(255);
            maxPowerSlider->textsize(14);
            maxPowerSlider->align(Fl_Align(FL_ALIGN_LEFT));
          } // Fl_Value_Slider* maxPowerSlider
          { travelSpeedSlider = new Fl_Spinner(390, 305, 160, 30, gettext("Travel speed"));
            travelSpeedSlider->maximum(5000);
            travelSpeedSlider->step(100);
            travelSpeedSlider->value(3000);
          } // Fl_Spinner* travelSpeedSlider
          { engravingSpeedSlider = new Fl_Spinner(390, 340, 160, 30, gettext("Engraving speed"));
            engravingSpeedSlider->maximum(5000);
            engravingSpeedSlider->value(5000);
          } // Fl_Spinner* engravingSpeedSlider
          { numPassesSlider = new Fl_Spinner(390, 380, 160, 20, gettext("Passes"));
          } // Fl_Spinner* numPassesSlider
          { outputFileNameInput = new Fl_Input(350, 450, 160, 25, gettext("Output file"));
          } // Fl_Input* outputFileNameInput
          { generateGcodeButton = new Fl_Button(520, 455, 70, 20, gettext("Generate"));
            generateGcodeButton->callback((Fl_Callback*)cb_generateGcodeButton);
          } // Fl_Button* generateGcodeButton
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(265, 300, 165, 15, gettext("SVG"));
          o->hide();
          o->deactivate();
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Tabs* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(10, 50, 195, 180, gettext("Loaded image"));
      o->box(FL_THIN_DOWN_FRAME);
      { loadedImageBox = new Fl_Box(26, 50, 170, 169);
      } // Fl_Box* loadedImageBox
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(5, 260, 200, 270, gettext("Drawer"));
      o->box(FL_DOWN_BOX);
      { Fl_Choice* o = new Fl_Choice(65, 270, 135, 20, gettext("Drawer"));
        o->down_box(FL_BORDER_BOX);
        if (!menu_Drawer_i18n_done) {
          int i=0;
          for ( ; i<2; i++)
            if (menu_Drawer[i].label())
              menu_Drawer[i].label(gettext(menu_Drawer[i].label()));
          menu_Drawer_i18n_done = 1;
        }
        o->menu(menu_Drawer);
      } // Fl_Choice* o
      o->end();
    } // Fl_Group* o
    mainWindow->end();
  } // Fl_Window* mainWindow
}

void FltkGui::runEventLoop(int argc, char** argv) {
  mainWindow->show(argc, argv);
  
  while (! quit && Fl::wait())
  {
    // Handle events or other actions here
  }
}

void FltkGui::stopEventLoop() {
  quit = true;
}

void FltkGui::openJpegImage() {
  Fl_Native_File_Chooser chooser;
  chooser.title("Open File");
  chooser.type(Fl_Native_File_Chooser::BROWSE_FILE);
      
  // Set filters for .jpg and .jpeg files
  chooser.filter("JPEG Image Files\t*.{jpg,jpeg}");
  
  switch (chooser.show())
  {
    case -1: // Error
      fprintf(stderr, "Error: %s\n", chooser.errmsg());
      break;
    case 1: // Cancel
      break;
    default: // File selected
    {
      printf("Selected file: %s\n", chooser.filename());
      Fl_JPEG_Image *image = new Fl_JPEG_Image(chooser.filename());
      if(image)
      {
        loadedImageBox->image(image);
        loadedImageBox->redraw();
        selectedInputImagePath = chooser.filename();
      }
      else
      {
        printf("Error loading image.\n");
      }
      break;
    }
  }
}

void FltkGui::displayErrorMessage(const std::string& message) {
  printf("TODO: error popup with %s!\n", message.c_str());
}
