name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libspdlog-dev libfltk1.3-dev libjpeg-dev g++ cmake
    - name: Install Boost 1.75.0
      run: |
        BOOST_VERSION=1.75.0
        BOOST_SRC_DIR=$HOME/boost_src_$BOOST_VERSION
        BOOST_INSTALL_DIR=$HOME/boost_$BOOST_VERSION
        BOOST_URL="https://boostorg.jfrog.io/artifactory/main/release/$BOOST_VERSION/source/boost_${BOOST_VERSION//./_}.tar.bz2"

        wget -O boost.tar.bz2 $BOOST_URL
        tar --bzip2 -xf boost.tar.bz2
        mv boost_${BOOST_VERSION//./_} $BOOST_SRC_DIR
        cd $BOOST_SRC_DIR
        ./bootstrap.sh --prefix=$BOOST_INSTALL_DIR
        ./b2 install
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DBOOST_ROOT=$BOOST_INSTALL_DIR -DBoost_NO_SYSTEM_PATHS=ON
    - name: Build
      run: |
        cd build
        make
#    - name: Test
#      run: |
#        ./path/to/your/tests
